### ISSUE TITLE
provide example pdf-viewer.html

### ISSUE THREAD

**Issue by alfredoivan** [tobyshooters/CS_Store#1]
can you provide example of pdf-viewer.html as seen in blog post https://cristobal.space/writing/folk ?

long story:
The pdf-viewer.html example you provide in the
https://cristobal.space/writing/folk blog post is excellent, would be
useful if you could put it in the github repo.

I've looked for that kind of stuff for a long time, even started writing
myself small scripts to do just that. Thus it would help kickstart that
and similar canvas oriented (more human oriented) software.

**Comment by alfredoivan** [comment]
the pdf-viewer.html was already put in the blog post and is unrelated to the cs_store project, my mistake. have a nice day.

**Comment by tobyshooters** [comment]
Glad you found that, appreciate the read :)
